version: 2.1

orbs:
  tf: circleci/terraform@3.1.0

jobs:
  tf-test:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: medium
    steps:
      - checkout
      - tf/install:
          terraform_version: '1.3.1'
      - tf/init
      - tf/fmt
      - tf/validate
      - tf/apply:
          var: 'postgresdb_container_mount_source=/home/circleci/project/postgres/init'
      - run: |
          docker ps

          docker container run --network learntf \
            -v $(pwd)/postman_collections:/etc/newman -t postman/newman run /etc/newman/Postgrest.json
      - tf/destroy:
          var: 'postgresdb_container_mount_source=/home/circleci/project/postgres/init'

workflows:
  main:
    jobs:
      - tf-test
