version: 2.1

orbs:
  tf: circleci/terraform@3.2.0

executors:
  basic:
    docker:
      - image: cimg/base:current
    resource_class: medium
jobs:
  tf-test:
    parameters:
      exec:
        type: executor
    executor: <<parameters.exec>>
    steps:
      - checkout
      - tf/install:
          terraform_version: '1.3.1'

workflows:
  main:
    jobs:
      - tf-test:
          matrix:
            parameters:
              exec:
                - basic
                - tf/default
