version: 2.1

orbs:
  tf: circleci/terraform@3.1.0

executors:
  tf:
    resource_class: kelvintaywl/cntr-agent-orange
    docker:
      - image: hashicorp/terraform
        entrypoint: /bin/sh

jobs:
  tf-container-runner:
    executor: tf
    steps:
      - run: ls
      - checkout
      - run: |
          terraform version

workflows:
  main:
    jobs:
      - tf-container-runner
