version: 2.1

# orbs:
#   tf: circleci/terraform@3.2.0

jobs:
  tf-install:
    docker:
      - image: cimg/go:1.16
    resource_class: small
    steps:
      # alternatively, use Terraform Orb's install command
      # see https://circleci.com/developer/orbs/orb/circleci/terraform#commands-install
      - run:
          name: Install Terraform
          command: |
            sudo curl https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_amd64.zip -o /tmp/terraform.zip
            sudo unzip /tmp/terraform.zip
            sudo mv ./terraform /usr/bin/
            sudo chmod +x /usr/bin/terraform

      - run:
          name: Verify
          command: |
            which terraform
            terraform version

workflows:
  main:
    jobs:
      - tf-install
